background      = [252, 252, 252, 255]
place_preview   = [128, 128, 128, 128]
copy_preview    = [255, 255, 255, 128]
selection_start = [26, 107, 237, 128]
selection_end   = [72, 97, 138, 128]
selection_box   = [66, 136, 245, 128]
input_preview   = [217, 159, 0, 255]
selected_ui     = [128, 128, 128, 64]
ui_bg           = [234, 235, 235, 255]
grid            = [232, 217, 203, 255]
